#!/usr/bin/env node

/**
 * Generates public/sw.js with a full list of precache URLs
 * derived from the content directory structure.
 *
 * Run: node scripts/generate-sw.mjs
 * Runs automatically via the "prebuild" npm script.
 */

import { readdirSync, statSync, writeFileSync } from "fs";
import { join, basename, extname } from "path";
import { fileURLToPath } from "url";

const ROOT = join(fileURLToPath(import.meta.url), "../..");
const CONTENT_DIR = join(ROOT, "content");
const OUTPUT = join(ROOT, "public/sw.js");

const LOCALES = ["en", "tl-ph"];

function getUrls() {
  const urls = new Set();

  // Static assets
  urls.add("/img/sos-logo.png");
  urls.add("/manifest.json");

  for (const locale of LOCALES) {
    // Home page for each locale
    urls.add(`/${locale}`);

    const localeDir = join(CONTENT_DIR, locale);
    let categories;
    try {
      categories = readdirSync(localeDir).filter((f) =>
        statSync(join(localeDir, f)).isDirectory()
      );
    } catch {
      console.warn(`Warning: locale directory not found: ${localeDir}`);
      continue;
    }

    for (const category of categories) {
      // Category listing page
      urls.add(`/${locale}/${category}`);

      const catDir = join(localeDir, category);
      const files = readdirSync(catDir).filter((f) => {
        const ext = extname(f);
        return (ext === ".mdx" || ext === ".md") && !f.startsWith("_");
      });

      for (const file of files) {
        const slug = basename(file, extname(file));
        urls.add(`/${locale}/${category}/${slug}`);
      }
    }
  }

  return [...urls].sort();
}

function generateSW(urls) {
  const urlList = urls.map((u) => `  "${u}"`).join(",\n");

  return `// AUTO-GENERATED by scripts/generate-sw.mjs — do not edit by hand
const CACHE_NAME = "lessons-v2";

const PRECACHE_URLS = [
${urlList},
];

self.addEventListener("install", (event) => {
  event.waitUntil(
    caches.open(CACHE_NAME).then((cache) => cache.addAll(PRECACHE_URLS))
  );
  self.skipWaiting();
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches.keys().then((keys) =>
      Promise.all(keys.filter((k) => k !== CACHE_NAME).map((k) => caches.delete(k)))
    )
  );
  self.clients.claim();
});

self.addEventListener("fetch", (event) => {
  if (event.request.method !== "GET") return;

  event.respondWith(
    caches.match(event.request).then((cached) => {
      const fetchPromise = fetch(event.request)
        .then((response) => {
          if (response.ok) {
            const clone = response.clone();
            caches.open(CACHE_NAME).then((cache) => cache.put(event.request, clone));
          }
          return response;
        })
        .catch(() => cached);

      return cached || fetchPromise;
    })
  );
});

// --- Client messaging ---

self.addEventListener("message", (event) => {
  if (!event.data || !event.data.type) return;

  if (event.data.type === "GET_CACHE_STATUS") {
    caches.open(CACHE_NAME).then(async (cache) => {
      const keys = await cache.keys();
      event.source.postMessage({
        type: "CACHE_STATUS",
        cached: keys.length,
        total: PRECACHE_URLS.length,
      });
    });
  }

  if (event.data.type === "REFRESH_CACHE") {
    caches.open(CACHE_NAME).then(async (cache) => {
      let completed = 0;
      for (const url of PRECACHE_URLS) {
        try {
          const response = await fetch(url, { cache: "no-cache" });
          if (response.ok) {
            await cache.put(url, response);
          }
        } catch {
          // Skip failed URLs — they'll be retried next time
        }
        completed++;
        // Send progress updates every 5 URLs
        if (completed % 5 === 0 || completed === PRECACHE_URLS.length) {
          self.clients.matchAll().then((clients) => {
            clients.forEach((client) => {
              client.postMessage({
                type: "REFRESH_PROGRESS",
                completed,
                total: PRECACHE_URLS.length,
              });
            });
          });
        }
      }
      // Final status
      self.clients.matchAll().then((clients) => {
        clients.forEach((client) => {
          client.postMessage({ type: "REFRESH_DONE" });
        });
      });
    });
  }
});
`;
}

const urls = getUrls();
const sw = generateSW(urls);
writeFileSync(OUTPUT, sw);
console.log(`Generated sw.js with ${urls.length} precache URLs`);
